# Generated by Django 2.1.7 on 2019-03-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0018_auto_20190307_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='solicitante',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
