# Generated by Django 2.1.7 on 2019-03-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0019_ticket_solicitante'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='municipio',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
