# Generated by Django 2.1.7 on 2019-03-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0020_ticket_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='municipio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='solicitante',
            field=models.CharField(max_length=50),
        ),
    ]
