# Generated by Django 2.1.7 on 2019-03-11 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0021_auto_20190311_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='municipio',
            new_name='entidade',
        ),
    ]
