# Generated by Django 2.1.7 on 2019-04-01 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0023_ticket_tipo_de_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='tipo_de_item',
            new_name='tipo_de_suporte',
        ),
    ]
